In [1]:
import numpy as np

In [8]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))

In [9]:
print(X)

[[ 10.57318974  -7.20131172 -11.36766898 ...   6.98166022  -4.30713427
  -21.13523828]
 [ -7.39706767   1.45132507  -5.6768415  ...  -1.80010401  -5.09045089
    4.84502194]
 [ -3.84693773  -3.39646717  -4.11819584 ...   4.30041127   0.82615656
  -12.15424901]
 ...
 [ 11.87899116  14.25531589  -1.8209125  ...   2.0597156  -21.48801449
   -3.75048004]
 [ 11.8455227  -14.50905934 -12.75519311 ...  -4.86707798   4.63440439
    1.89460842]
 [ -1.88924639  -3.25890563   1.46528003 ... -19.98366374  21.35504755
  -14.12430899]]


In [10]:
m = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print (X_norm)

[[ 0.98578107 -0.82709894 -1.38301747 ...  0.63434086 -0.53570624
  -2.18907757]
 [-0.85248118  0.0649668  -0.77660268 ... -0.26621877 -0.6115861
   0.38237987]
 [-0.48932167 -0.43482876 -0.61051334 ...  0.35938192 -0.03844447
  -1.300163  ]
 ...
 [ 1.11935765  1.38502701 -0.36571474 ...  0.1296012  -2.20001773
  -0.46838018]
 [ 1.115934   -1.58050989 -1.53087209 ... -0.58073336  0.33046041
   0.09035574]
 [-0.2890602  -0.4206465  -0.01553795 ... -2.13092152  1.95018875
  -1.49515433]]


In [11]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [12]:
print (Z)

[[4 5 0]
 [1 9 3]
 [5 1 1]
 [3 3 3]
 [9 9 9]
 [4 7 1]]


In [20]:
r = np.sum(Z, axis=1)
print(r)
print (np.nonzero(r > 10))

[ 9 13  7  9 27 12]
(array([1, 4, 5]),)


In [21]:
A = np.eye(3)
B = np.eye(3)
print (A)
print (B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
AB = np.vstack((A, B))
print (AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
